### ISSUE TITLE
Converting yaml files to pandas df fails

### ISSUE THREAD

**Issue by skwolvie** [tvganesh/yorkpy#2]
**Converting yaml files to pandas df fails**

yka.convertAllYaml2PandasDataframesT20("YamlDtsets//INTLT20_YAML_Dtsets", "..//..//IntlT20//IntlT20-Matches")

[convertAllYaml2PandasDataframesT20]
- Fails to convert all YAML files in the source directory and save csv in the destination directory

[logs/screenshots]

File no= 0
Converting file: 1001349.yaml
C:\Users\sachi\Anaconda3\lib\site-packages\yorkpy\analytics.py:76: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  a=yaml.load(f)
C:\Users\sachi\Anaconda3\lib\site-packages\yorkpy\analytics.py:87: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  team1=pd.concat([team1,b])
Team1:diff: ['penalty']
team1: penalty
C:\Users\sachi\Anaconda3\lib\site-packages\yorkpy\analytics.py:145: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  team2=pd.concat([team2,b])
Team2:diff: ['penalty', 'noballs']
team2: penalty
team2: noballs
Team1-missing columns: []
Team2-missing columns: []
Length of info field= 10
Wintype= wickets
Win value= wickets
win margin= 5
..//..//IntlT20//IntlT20-Matches\Australia-Sri Lanka-2017-02-17.csv
Dataframe shape= (250, 38)

File no= 1
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-06b6a4d7924e> in <module>
----> 1 yka.convertAllYaml2PandasDataframesT20("YamlDtsets//INTLT20_YAML_Dtsets", "..//..//IntlT20//IntlT20-Matches")

~\Anaconda3\lib\site-packages\yorkpy\analytics.py in convertAllYaml2PandasDataframesT20(source, dest)
    379          print("\n\nFile no=",index)
    380          if file.endswith(".yaml"):
--> 381              df, filename = convertYaml2PandasDataframeT20(file, source, dest)
    382              #print(filename)
    383 

~\Anaconda3\lib\site-packages\yorkpy\analytics.py in convertYaml2PandasDataframeT20(infile, source, dest)
     68     '''
     69 
---> 70     os.chdir(source)
     71     os.path.join(source,infile)
     72 

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'YamlDtsets//INTLT20_YAML_Dtsets'

![image](https://user-images.githubusercontent.com/22741452/77995597-bbdf4580-7349-11ea-8eaf-cd97e061e366.png)
![image](https://user-images.githubusercontent.com/22741452/77995612-c4d01700-7349-11ea-8bf6-30682fea9672.png)

**Comment by tvganesh** [comment]
It looks like a "File not found error'. Make sure the path is correct.

"FileNotFoundError: [WinError 3] The system cannot find the path specified: 'YamlDtsets//INTLT20_YAML_Dtsets'"

It looks like the conversion has happened
..//..//IntlT20//IntlT20-Matches\Australia-Sri Lanka-2017-02-17.csv
Dataframe shape= (250, 38)
Of shape 250,38

**Comment by skwolvie** [comment]
My analogy of what is happening in the code is:
It goes from CWD to _YamlDtsets//INTLT20_YAML_Dtsets_ picks up the first file converts it and then it tries to search and navigate to dir _YamlDtsets//INTLT20_YAML_Dtsets_ from CWD i.e, YamlDtsets//INTLT20_YAML_Dtsets. 

Is it correct?

And also once it goes to the given source dir it is not returning to Project home directory after the code fails. 
Examining with os.getcwd() returns cwd as source dir

**Comment by skwolvie** [comment]
The path is correct because after I execute the code, and it failed, I ran os.getcwd(), and I was present in the Source directory
