### ISSUE TITLE
teamBatsmenPartnershipOppnAllMatchesChart has argumet savePic mismatch in definition

### ISSUE THREAD

**Issue by skwolvie** [tvganesh/yorkpy#4]
def teamBatsmenPartnershipOppnAllMatchesChart(matches,main,opposition,plot=True,top=5,partnershipRuns=20, **_avePic=False_**, dir1=".",picFile="pic1.png"):
.....
'''''
if(**_savePic_**):
            plt.savefig(os.path.join(dir1,picFile),bbox_inches='tight')
.....
......

[error during execution]

-NameError                                 Traceback (most recent call last)
<ipython-input-27-f28f86fc6c47> in <module>
----> 1 yka.teamBatsmenPartnershipOppnAllMatchesChart(rcb,'Royal Challengers Bangalore','Chennai Super Kings',plot=True,top=5,partnershipRuns=20)

~\anaconda3\lib\site-packages\yorkpy\analytics.py in teamBatsmenPartnershipOppnAllMatchesChart(matches, main, opposition, plot, top, partnershipRuns, avePic, dir1, picFile)
   1534        plt.xlabel('Batsman')
   1535        plt.ylabel('Partnership runs')
-> 1536        if(savePic):
   1537             plt.savefig(os.path.join(dir1,picFile),bbox_inches='tight')
   1538        else:

NameError: name 'savePic' is not defined

**Comment by tvganesh** [comment]
The functions have changes. Use help.
